### PR TITLE
Add no-unused-vars rule

### PR DESCRIPTION
**Pull request by darrenmce**
Seemed odd that this isn't in, snuck through the cracks?

http://eslint.org/docs/rules/no-unused-vars.html

### CODE REVIEW

**Comment by mpareja** [comment]
I'm shocked that unused vars weren't being called out, doh!

Merging this in may result in a plethora of build failures. When do y'all recon would be a good time to merge this and how can we jump on fixing the issues? @360incentives/developers

**Comment by travispickard** [comment]
we have two issues right now that we need to address and will require deployment of Utopia and Atlas today.

**Comment by darrenmce** [comment]
@mpareja let em fail? shouldn't be hard to fix these (even in buck, which has a million of these)

**Comment by snypelife** [comment]
`--fix` ?

**Comment by darrenmce** [comment]
@mpareja bump!

**Comment by snypelife** [comment]
image

**Comment by prime8** [comment]
What Brett said: merge it in; watch for the build failures; then fix whatever needs fixing...

**Pull request merged**
